---

services:

  traefik:
    container_name: base_traefik
    image: traefik:v2.11.2
    # command: moved to environment variables traefik.env
    security_opt:
      - "no-new-privileges:true"
    ports:
      - "${ENV_TRAEFIK_IP:-}:80:80"
      - "${ENV_TRAEFIK_IP:-}:443:443"
    networks:
      - frontend
      - backend
    volumes:
      - "./traefik-config/:/config/"
      - "./traefik-certs/:/certs/"
      - "./traefik-certs/acme.json:/etc/letsencrypt/acme.json"
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - ENV_TRAEFIK_HOST
      - ENV_TRAEFIK_IP
      - ENV_TRAEFIK_EMAIL
      - ENV_TRAEFIK_REALM
      - ENV_TRAEFIK_IPALLOWLIST
    env_file:
      - "traefik.env"
    secrets:
      - traefik_secrets
    labels:
      - "traefik.enable=true"
      # force https and redirect http
      - "traefik.http.routers.http-catchall.entrypoints=web"
      - "traefik.http.routers.http-catchall.rule=hostregexp(`{host:.+}`)"
      - "traefik.http.routers.http-catchall.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      # configure traefik with path prefix and letencrypt
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.tls=true"
      - "traefik.http.routers.traefik.tls.certresolver=leresolver"
      - "traefik.http.routers.traefik.rule=Host(`${ENV_TRAEFIK_HOST:-localhost}`) && PathPrefix(`/traefik`) \
                    || Headers(`Referer`, `https://${ENV_TRAEFIK_HOST:-localhost}/traefik/dashboard/`)"
      - "traefik.http.middlewares.traefik-strip.stripprefix.prefixes=/traefik"
      - "traefik.http.routers.traefik.middlewares=chain-ipallowlist-auth@file,traefik-strip,error-pages@file"
      - "traefik.http.routers.traefik.service=api@internal"

  portainer:
    container_name: base_portainer
    image: portainer/portainer-ce:2.20.1-alpine
    security_opt:
      - "no-new-privileges:true"
    command:
      - '--admin-password-file=/run/secrets/portainer_admin_secret'
    networks:
      - backend
    volumes:
      - "base_portainer_data:/data"
      - "/var/run/docker.sock:/var/run/docker.sock"
    secrets:
      - portainer_admin_secret
      - portainer
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.entrypoints=websecure"
      - "traefik.http.routers.portainer.tls=true"
      - "traefik.http.routers.portainer.tls.certresolver=leresolver"
      - "traefik.http.routers.portainer.rule=Host(`${ENV_TRAEFIK_HOST:-localhost}`) && PathPrefix(`/portainer`)"
      - "traefik.http.middlewares.portainer-strip.stripprefix.prefixes=/portainer"
      - "traefik.http.middlewares.portainer-strip.stripprefix.forceSlash=true"
      - "traefik.http.routers.portainer.middlewares=chain-ipallowlist@file,portainer-strip,error-pages@file"
      - "traefik.http.routers.portainer.service=portainer"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"

  nginx:
    container_name: base_nginx
    image: nginx:1.25.1-alpine3.17-slim
    security_opt:
      - "no-new-privileges:true"
    networks:
      - backend
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "./nginx/html:/etc/nginx/html"
      - "./nginx/error-pages:/usr/share/nginx/error-pages"
    environment:
      # You can silence entrypoint logs by setting this environment variable
      - "NGINX_ENTRYPOINT_QUIET_LOGS=1"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx.entrypoints=websecure"
      - "traefik.http.routers.nginx.tls=true"
      - "traefik.http.routers.nginx.tls.certresolver=leresolver"
      - "traefik.http.routers.nginx.rule=HostRegexp(`{host:.+}`)"
      - "traefik.http.routers.nginx.priority=1"
      - "traefik.http.routers.nginx.middlewares=chain-basic@file"
      - "traefik.http.services.error-pages-service.loadbalancer.server.port=80"

  whoami:
    container_name: base_whoami
    image: traefik/whoami:v1.10.1
    security_opt:
      - "no-new-privileges:true"
    networks:
      - backend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.entrypoints=websecure"
      - "traefik.http.routers.whoami.rule=Host(`${ENV_TRAEFIK_HOST:-localhost}`) && PathPrefix(`/whoami`)"
      - "traefik.http.routers.whoami.tls=true"
      - "traefik.http.routers.whoami.tls.certresolver=leresolver"
      - "traefik.http.routers.whoami.middlewares=chain-ipallowlist@file,error-pages@file"

volumes:
  base_portainer_data:
    external: true

networks:
  frontend:
    external: true
  backend:
    external: true

secrets:
  traefik_secrets:
    file: ./.traefik_secrets.txt
  portainer_admin_secret:
    file: ./.portainer_admin_secret.txt
  portainer:
    file: ./.portainer_key_secret.txt

...
